"""Added Posts Model

Revision ID: 449d3c364ab8
Revises: 7841c3234ba3
Create Date: 2022-11-24 17:46:20.956062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449d3c364ab8'
down_revision = '7841c3234ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
