"""Blog model new

Revision ID: 475eaa83911d
Revises: 5c8a53b0cf33
Create Date: 2022-11-24 17:50:28.589639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475eaa83911d'
down_revision = '5c8a53b0cf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
